apiVersion: v1
kind: Service
metadata:
  name: ghost
spec:
  type: LoadBalancer   
  selector:
    app: ghost
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 2368  
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  strategy:
    type: Recreate 
  replicas: 1 
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:5-alpine
        env:
        - name: url
          value: https://blog.dl4it.com
        - name: database__client
          value: "mysql"
        - name: database__connection__host
          value: "mysql" 
        - name: database__connection__user
          value: "ghost" # Use the dedicated ghost user
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: ghost-db-secrets
              key: mysql-password # Use the user password, not root
        - name: database__connection__database
          value: "ghost"
        ports:
        - containerPort: 2368
        volumeMounts:
        - name: ghost-content
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-content
        persistentVolumeClaim:
          claimName: ghost-content-pvc