name: Cloud-Native Stack Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: HashiCorp Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Validate
        run: |
          terraform init -backend=false
          terraform validate
        working-directory: ./terraform

  deploy:
    needs: terraform-check
    runs-on: self-hosted  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Manifests
        run: |
          # Pointing to the local K3s config on your master node
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          
          # Apply the entire kubernetes directory to ensure everything stays in sync
          kubectl apply -f kubernetes/